version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: capstoneimg
    ports:
      - "82:80"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    volumes:
      - ./path/on/host:/path/in/container
